### Add test data
POST http://localhost:5227/api/courses/seed-test-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyIiwidW5pcXVlX25hbWUiOiJpYnJhaGVtIiwiZW1haWwiOiJpYnJhaGVtc2F5ZWQ0MzNAZ21haWwuY29tIiwicm9sZSI6IjEiLCJCcmFuY2hJZCI6IjEiLCJGdWxsTmFtZSI6Itil2KjYsdin2YfZitmFINiz2YrYryIsIm5iZiI6MTc1MjU1NDg4NywiZXhwIjoxNzUyNjQxMjg3LCJpYXQiOjE3NTI1NTQ4ODcsImlzcyI6IkFJUm9ib3RpY3NBY2FkZW15IiwiYXVkIjoiQUlSb2JvdGljc0FjYWRlbXlVc2VycyJ9.HOrPtNocmE970bjl2yYkYEeCinuElBKSh-P3I5LaYow
Content-Type: application/json
 
### Get course 1 details
GET http://localhost:5227/api/courses/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyIiwidW5pcXVlX25hbWUiOiJpYnJhaGVtIiwiZW1haWwiOiJpYnJhaGVtc2F5ZWQ0MzNAZ21haWwuY29tIiwicm9sZSI6IjEiLCJCcmFuY2hJZCI6IjEiLCJGdWxsTmFtZSI6Itil2KjYsdin2YfZitmFINiz2YrYryIsIm5iZiI6MTc1MjU1NDg4NywiZXhwIjoxNzUyNjQxMjg3LCJpYXQiOjE3NTI1NTQ4ODcsImlzcyI6IkFJUm9ib3RpY3NBY2FkZW15IiwiYXVkIjoiQUlSb2JvdGljc0FjYWRlbXlVc2VycyJ9.HOrPtNocmE970bjl2yYkYEeCinuElBKSh-P3I5LaYow 